# Generated by Django 2.2.19 on 2022-09-02 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post_list', '0004_auto_20220901_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='slug',
        ),
        migrations.AddField(
            model_name='thread',
            name='thread_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='thread',
            field=models.ForeignKey(blank=True, help_text='Тред, к которой будет относиться пост', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thread', to='post_list.Thread', verbose_name='Тред'),
        ),
    ]
