# Generated by Django 2.2.19 on 2022-09-02 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_list', '0005_auto_20220902_1103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ['-thread_number'], 'verbose_name': 'Тред', 'verbose_name_plural': 'Треды'},
        ),
        migrations.RemoveField(
            model_name='thread',
            name='description',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='title',
        ),
    ]
